export const texts = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lacinia, ligula quis dapibus rhoncus, lectus lorem venenatis eros, non vehicula risus quam et leo. Cras bibendum fermentum purus, a consectetur dolor condimentum sed. Aenean ac rhoncus mauris, eget efficitur nisi. Vivamus pellentesque nisi sit amet felis facilisis, in elementum dolor varius. Praesent vitae ex at massa imperdiet pretium.",
  "Quisque quis nunc dictum, accumsan orci sed, venenatis tellus. Proin ac arcu enim. Donec malesuada quam non urna egestas iaculis. Suspendisse tincidunt placerat massa, eu lobortis nisi vulputate ac. Morbi condimentum lectus at hendrerit lobortis. Maecenas pretium odio nec turpis viverra, a luctus nisi aliquet. Nulla quis lacus quis sapien auctor efficitur in eget ligula. Fusce tristique, elit et dapibus tempor, ante velit aliquam arcu, sed gravida tellus felis sit amet ligula.",
  "Donec porttitor eros nulla, nec eleifend nibh sagittis et. Donec neque felis, congue a ultricies sed, vehicula at lorem. Maecenas vehicula eleifend turpis eget pellentesque. Phasellus eget sollicitudin tellus. Praesent non enim quis diam fringilla placerat in ac enim. Suspendisse elit justo, mattis vel dolor eu, varius ornare leo. Quisque felis ex, gravida vel urna vel, varius gravida lectus. Duis ac felis est. Aenean eu urna imperdiet, condimentum augue sit amet, auctor dui.",
  "Suspendisse potenti. Pellentesque dignissim metus enim, ac faucibus lectus euismod vitae. Aenean dictum vulputate urna at vulputate. Donec eget tristique neque, id mattis felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus condimentum elementum nibh, eget gravida sem. Mauris consectetur, diam porta laoreet consectetur, enim arcu sodales leo, in suscipit nisi enim quis mauris. Suspendisse quis suscipit metus. Maecenas vel erat vitae enim maximus vulputate nec eu dolor.",
  "Vivamus porta malesuada leo, nec tempor arcu pellentesque quis. Vivamus condimentum semper orci iaculis blandit. Nulla porttitor, lorem vitae tincidunt interdum, nulla turpis tincidunt risus, ac condimentum dui sem ac velit. Maecenas nec elementum velit. Curabitur malesuada dui id orci viverra pharetra. Duis maximus elit ut nibh accumsan, et viverra orci rhoncus. Cras arcu justo, pretium ut convallis at, pharetra eget ex.",
  "Maecenas luctus sit amet turpis sed tempus. Nulla tempus erat arcu, nec volutpat purus auctor ac. Cras mattis nunc nunc. Pellentesque suscipit lacinia ligula. Duis ultrices dolor est, nec hendrerit sapien gravida non. Ut iaculis odio in tempor dapibus. Integer dictum vehicula tincidunt. Aenean elementum, orci quis efficitur venenatis, turpis orci finibus libero, vel volutpat mauris massa id ligula. In hac habitasse platea dictumst. Nulla facilisi. Curabitur in felis massa.",
  "In viverra scelerisque diam vel vestibulum. Vivamus pulvinar velit sapien, a semper felis accumsan ac. Nullam nec dapibus odio. Fusce dignissim leo ac nunc aliquam, at volutpat augue suscipit. Donec gravida gravida feugiat. Nunc id sagittis massa, id malesuada magna. Nunc mattis, elit vitae efficitur dictum, dui enim consequat massa, vitae ullamcorper nisi mi in quam.",
  "Example text",
];

export default { texts };
